apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.appname }}
  namespace: {{ .Values.global.destination.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.appname }}
      {{- include "workouts-chart.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.appname }}
        {{- include "workouts-chart.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.backend.appname }}
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: DB_PASSWORD
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-db-secret
              key: ADMIN_TOKEN
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.backend.configmap.name }}
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.backend.configmap.name }}
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.backend.configmap.name }}
              key: DB_NAME

        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.service.port }}
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}