apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.appname }}
spec:
  selector:
    app: {{ .Values.backend.appname }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}