apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.appname }}
  namespace: {{ .Values.global.destination.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: {{ .Values.frontend.appname }}