apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.appname }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.appname }}
      {{- include "workouts-chart.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appname }}
        {{- include "workouts-chart.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.frontend.appname }}
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
        resources:
          limits:
            memory: {{ .Values.frontend.resources.limits.memory }}
            cpu: {{ .Values.frontend.resources.limits.cpu }}
          requests:
            memory: {{ .Values.frontend.resources.requests.memory }}
            cpu: {{ .Values.frontend.resources.requests.cpu }}